backend:
  name: git-gateway # or "github" / "gitlab"
  branch: master

media_folder: "src/images" # where uploads are stored in the repo
public_folder: "/images" # how the site references those images

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true # <— for local development

# ───────────────────────────────────────────────────────────────
collections:
  # ── Static single‑file pages ─────────────────────────────────
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/index.njk"
        extension: "njk"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "About Page"
        name: "about"
        file: "src/pages/about.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Blog Listing"
        name: "blog-listing"
        file: "src/blog.njk" # moved from src/blog/index.md
        extension: "njk"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Newsletter Listing"
        name: "newsletter-listing"
        file: "src/newsletter.njk" # moved from src/newsletters/index.md
        extension: "njk"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Gallery Listing"
        name: "gallery-listing"
        file: "src/gallery.njk" # moved from src/galleries/index.md
        extension: "njk"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }
  # ── Blog posts ──────────────────────────────────────────────
  - name: "blog"
    label: "Blog"
    folder: "src/blog" # ← must match that folder name
    create: true
    extension: "md" # ← or "njk" if you converted them
    format: "frontmatter" # ← so CMS knows to parse `---` YAML
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # ── Newsletters ──────────────────────────────────────────────
  - name: "newsletters"
    label: "Newsletters"
    folder: "src/newsletters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF", name: "file", widget: "file", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # ── Galleries ────────────────────────────────────────────────
  - name: "galleries"
    label: "Galleries"
    folder: "src/galleries"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false
        }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }

  # ── ★ NEW ★ Team Members ───────────────────────────────
  - name: "team"
    label: "Team Members"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          value_type: "int",
          required: false
        }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
